export const DeviceTypeName = {
    alarm: 'alarm',
    alarmHost: 'alarmhost',
    call: 'call',
    callHost: 'callhost',
    camera: 'camera',
    decoderChannel: 'decoderchannel',
    dm: 'dm',
    doorPoint: 'doorpoint',
    door: 'door',
    envMonitor: 'envmonitor',
    led: 'led',
    matrix: 'matrix',
    matrixChannel: 'matrixchannel',
    powergridHost: 'powergridhost',
    powergrid: 'powergrid',
    relay: 'relay',
    relayHost: 'relayhost',
    rfidTag: 'rfidtag',
    tvwall: 'tvwall',
    tvwallChannel: 'tvwallchannel',
    ups: 'ups',
    videoAnalyse: 'videoanalyse',
    videoAnalyseChannel: 'videoanalysechannel',
    vm: 'vm'
};